### ISSUE TITLE
[Feature Request] Add Completion Percentage Statistics

### ISSUE THREAD

**Issue by lewxdev** [Benjamin-Norton/RandoAssistant#11]
This is a proposal for the addition of completion percentage statistics, which would display stats for the percentage of discovered to undiscovered loot. It may also be helpful to break it up by category to help players determine where to focus their attention (e.g. block, mob, container, misc).

```
Overall Completion: 25% (n/a)
Block Loot Completion: 12% (n/b)
Container Loot Commpletion: 3% (n/c)
Misc Loot Completion: 0% (n/d)
```

Additionally, by additionally tracking these statistics, a toast notification could be shown once a category reaches 100%. This way, players can easily know to divert their attention from a category that will no longer yield any new discoveries.

```
Discovered all block loot!
Try breaking some mobs?
```

**Comment by Benjamin-Norton** [comment]
Interesting idea. I'll give it a look when I'm a little less swamped.

**Comment by Benjamin-Norton** [comment]
Ok now that I finished basically re-writing the entire mod I can add this somewhere

**Comment by Benjamin-Norton** [comment]
Added in 1.2.0
