### ISSUE TITLE
[Bug Report] Version 1.0.0 and 1.0.1 crashing

### ISSUE THREAD

**Issue by TheGooodie** [Benjamin-Norton/RandoAssistant#15]
**Expected Behaviour**
Works with version 0.4.3

**Actual Behaviour**
Crashes on 1.0.0 and 1.0.1

**Steps to Reproduce**
- Using Simply Optimized Modrinth modpack (version 1.19.4-1.3.3)
- added Full Brightness Toggle and Random Assistant mods
- runs with RA 0.4.3 but fails when changed to 1.0.0 or 1.0.1

**What version of the mod are you using**
tested 0.4.3, 1.0.0 and 1.0.1

**Helpful Files**
[latest.log](https://github.com/Benjamin-Norton/RandoAssistant/files/11454739/latest.log)

**Comment by Benjamin-Norton** [comment]
Alright let me have a look, probably a compatibility issue with one of the mods in simply optimised.

**Comment by Benjamin-Norton** [comment]
It's fixed now, there were actually two bugs present, 1 was an issue w/ my mod by itself and another was a compat issue with c2me that I have now fixed.
