### ISSUE TITLE
[Bug Report] No version 1.0.0 and above launches

### ISSUE THREAD

**Issue by KYO297** [Benjamin-Norton/RandoAssistant#16]
I've tried every version from 1.0.0 to 1.0.3 with nothing else installed, the game crashes. 0.4.3 works, and so did at least 2 earlier version
[latest.log](https://github.com/Benjamin-Norton/RandoAssistant/files/11467606/latest.log)

**Comment by Benjamin-Norton** [comment]
Should be fixed, new release found here: https://github.com/Benjamin-Norton/RandoAssistant/releases/tag/release-5
It will be up on curseforge and modrinth shortly, let me know if the issue still persists

**Comment by KYO297** [comment]
Still crashes
[latest.log](https://github.com/Benjamin-Norton/RandoAssistant/files/11469706/latest.log)

also tried on a different PC with java 19 (instead of 8) istalled and it's the same (?) thing
[latest.log](https://github.com/Benjamin-Norton/RandoAssistant/files/11469724/latest.log)

**Comment by Benjamin-Norton** [comment]
Ok so both these crashes came from the same library I use in this mod. I have no idea why it's crashing for you as I can launch just fine. I'm going to look into this some more and see what's going on.

**Comment by Benjamin-Norton** [comment]
Try this one. https://github.com/Benjamin-Norton/RandoAssistant/releases/tag/release-6
I'll leave this open until you get back to me

**Comment by KYO297** [comment]
Thanks! It doesn't crash now, and as far as my 5 minute test can tell everything works fine. Though, I'm not sure if this is intended, breaking a block that drops nothing still reveals a drop table, one that'd normally require silk touch to figure out

**Comment by Benjamin-Norton** [comment]
Yeah thats a side effect of the new tracking system. I might overrule the unlock depending on feedback as the current system just tracks unlocking the loot table rather than the actual drops, which makes everything a lot more performance friendly.
