### ISSUE TITLE
[Bug Report] Server issue

### ISSUE THREAD

**Issue by EmlaSweetheart** [Benjamin-Norton/RandoAssistant#18]
![IMG_20230522_220107](https://github.com/Benjamin-Norton/RandoAssistant/assets/134331042/5acd9149-2962-4239-89c4-734f9e25ac6e)

1.0.7 works fine but after that I've received this same error when another user is trying to enter through multi-player. 

Could this be fixed because I love this mod and want to be able to enjoy the new features 😊

**Comment by Benjamin-Norton** [comment]
Probably fixed in [1.2.7](https://github.com/Benjamin-Norton/RandoAssistant/releases/tag/release-18)
