### ISSUE TITLE
[Discussion] State & Linking

### ISSUE THREAD

**Issue by Fasguy** [Benjamin-Norton/RandoAssistant#2]
I would like to add a link to this mod directly into the randomizer site.
Do you think the mod is in enough of a usable state to send people here directly or do you want me to wait until the first fully stable release gets published?

**Comment by Benjamin-Norton** [comment]
In its current state, per my testing, it should be stable and usable on a single-player world, I have not had the chance to test how it behaves on a dedicated server, but I have kept the sources separate so there shouldn't be an issue if it is used on a server. 
You can link to it but I would state that the mod is still in development as there may be some edge cases I haven't considered.
