### ISSUE TITLE
[Bug Report] Cannot Input Text

### ISSUE THREAD

**Issue by CokeStudios** [Benjamin-Norton/RandoAssistant#20]
**Expected Behaviour**
When I clicked on 'search' textbox or the textbox in the settings page, nothing happens on my mac.

**Actual Behaviour**
When I clicked on 'search' textbox or the textbox in the settings page, I can input something.

**What version of the mod are you using**
1.3.1

**Comment by Benjamin-Norton** [comment]
Fixed in 1.4.0
