### ISSUE TITLE
[Bug Report] <Description>

### ISSUE THREAD

**Issue by mal211** [Benjamin-Norton/RandoAssistant#24]
**Expected Behaviour**
When I open the Red Book and click on anything to see it's path, it brings up the big box at the top to show the pathway, there should be a way to close the menu.

**Actual Behaviour**
When I open the Red Book and click on anything to see it's path, it brings up the big box at the top to show the pathway, and it then cuts off part of my inventory and there is no way to close that screen besides, clicking the red book, but everytime I click the red book, it bring up the same big screen of the paths.
![Rando Assistant Mod error](https://github.com/Benjamin-Norton/RandoAssistant/assets/116613714/3e61a621-0c7b-4b5c-ad26-7c531c5de15e)

**Steps to Reproduce**
- Open minecraft with mod installed using curse forge
- open world
- open inventory
- open red book
- click on any item on the side to pull up paths
- error occurs

**What version of the mod are you using**
1.42 & 1.4.1

**Helpful Files**
Drag and drop these files here to help me figure out what broke.

- latest.log
  - Found in `.minecraft/logs`
[latest.log](https://github.com/Benjamin-Norton/RandoAssistant/files/11901263/latest.log)

**Comment by Benjamin-Norton** [comment]
Yeah, that's an issue w/ the gui scale. You will need to lower your gui scale by 1, I can't do much about it without re-writing the entire ui part, and I am very busy atm. Sorry.
