### ISSUE TITLE
Failed to draw graph

### ISSUE THREAD

**Issue by killerwombat02** [Benjamin-Norton/RandoAssistant#3]
[latest.log](https://github.com/Benjamin-Norton/RandoAssistant/files/10889734/latest.log)
Crafting a gold block into ingots then back into a block is what I did that broke it.

**Comment by Benjamin-Norton** [comment]
Yeah I see the issue, thought I fixed that, I'll work on a patch

**Comment by Benjamin-Norton** [comment]
Hmm, I can't reproduce. Can you send me the RandoAssistant files for your world. 
They are located in your .minecraft folder and the name of the files should be 
"datapack_seed".json and "datapack_seed_interactions".json

**Comment by Benjamin-Norton** [comment]
I think I found the cause and should be fixed in the next release. 
I'm going to leave this issue open until confirmed.

**Comment by killerwombat02** [comment]
[12345678910-RandoAssistant.zip](https://github.com/Benjamin-Norton/RandoAssistant/files/10890500/12345678910-RandoAssistant.zip)
Here are the files.

**Comment by Benjamin-Norton** [comment]
Ok yup, it renders fine with the new version. No crashing or failing.
