### ISSUE TITLE
Right Click Crash

### ISSUE THREAD

**Issue by killerwombat02** [Benjamin-Norton/RandoAssistant#5]
When I right click redstone dust in the graph it crashes the game.
[crash-2023-03-08_14.22.24-client.txt](https://github.com/Benjamin-Norton/RandoAssistant/files/10925731/crash-2023-03-08_14.22.24-client.txt)
[12345678910-RandoAssistant.zip](https://github.com/Benjamin-Norton/RandoAssistant/files/10925743/12345678910-RandoAssistant.zip)
[latest.log](https://github.com/Benjamin-Norton/RandoAssistant/files/10925745/latest.log)

**Comment by Benjamin-Norton** [comment]
This bug was patched in 0.2.5, please update your jar.

**Comment by killerwombat02** [comment]
It seems to still be happening, it also crashed when I searched it this time.
[crash-2023-03-08_15.48.15-client.txt](https://github.com/Benjamin-Norton/RandoAssistant/files/10926303/crash-2023-03-08_15.48.15-client.txt)
[12345678910-RandoAssistant.zip](https://github.com/Benjamin-Norton/RandoAssistant/files/10926305/12345678910-RandoAssistant.zip)
[latest.log](https://github.com/Benjamin-Norton/RandoAssistant/files/10926306/latest.log)

**Comment by Benjamin-Norton** [comment]
Ok, well this is odd. I can't reproduce this in my dev environment, even when using the same files

**Comment by killerwombat02** [comment]
Here is everything I am doing, perhaps I am doing something wrong?
[RandoAssistant crash video 01.zip](https://github.com/Benjamin-Norton/RandoAssistant/files/10926359/RandoAssistant.crash.video.01.zip)

**Comment by Benjamin-Norton** [comment]
hmmm, yeah, I do the same thing and no crash. I'll load up an instance of mc w/ jei and mousetweaks and see if it is a compatibility issue

**Comment by Benjamin-Norton** [comment]
Yeah no difference, I'll load it all into the curseforge client and try that

**Comment by Benjamin-Norton** [comment]
No crash in curseforge. I don't know what could be causing this. I'll try and guess how to fix this and post a patch, can you try re-creating the world with the same datapack?

**Comment by killerwombat02** [comment]
Here is the world file and the seed is 7941621229447362118
https://drive.google.com/file/d/1BfwO4UYPWLmMKyWY9IABj2B9QTZaD2qs/view?usp=sharing

**Comment by Benjamin-Norton** [comment]
Yeah, I can't reproduce. No crashing

[Screen Recording 2023-03-08 at 4.23.29 PM.mp4.zip](https://github.com/Benjamin-Norton/RandoAssistant/files/10926451/Screen.Recording.2023-03-08.at.4.23.29.PM.mp4.zip)

**Comment by Benjamin-Norton** [comment]
Could you try clearing your file with `j` and then unlocking all loot tables with `k` and tell me if that crashes then.

**Comment by killerwombat02** [comment]
Resetting and unlocking fixed it. I tried retracing my steps and unlocking redstone wire as I did before and it was fine.
My only guess is that I updated from the previous version after the bug had happened, I don't know how you coded it but maybe it didn't retroactively fix what was already broken?
Anyway thank you for trying.

**Comment by Benjamin-Norton** [comment]
Yeah, that's my best guess, the graph drawing / highlighting tasks are not straightforward and use their own threaded executors (for performance). This does mean that if they break, it is tough to figure out why or how. 

There may have been cached classes that weren't appropriately overwritten when updating, thus, leaving the old, bugged code in the Minecraft runtime.

Glad it's fixed.
