### ISSUE TITLE
Crash before launch

### ISSUE THREAD

**Issue by obayko** [Benjamin-Norton/RandoAssistant#6]
Hello, so I've tried everything I can think of, but my knowledge is limited. I've installed the jar files and I keep crashing every time I try to launch the game. The game starts fine upon the removal of randoassistant. (I'll also admit this is the first time I've used Fabric instead of Forge, but I'm able to load it fine with just Fabric and only the YACL mod installed.) I've looked at the log and this seems to be the root of the issue but I have no idea how to fix it. Help please?

Mixin apply for mod randoassistant failed randoassistant.client.mixins.json:InventoryScreenMixin from mod randoassistant -> net.minecraft.class_490: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> randoassistant.client.mixins.json:InventoryScreenMixin from mod randoassistant -> Apply Methods -> (Lnet/minecraft/class_4185;)V:md59eed5$randoassistant$lambda$onInit$0$1 -> Transform Instructions -> INVOKESPECIAL com/bawnorton/randoassistant/mixin/client/InventoryScreenMixin$1::<init>(Lcom/bawnorton/randoassistant/mixin/client/InventoryScreenMixin;Lio/github/cottonmc/cotton/gui/GuiDescription;)V -> desc=Lio/github/cottonmc/cotton/gui/GuiDescription;]
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Unexpecteded ClassMetadataNotFoundException whilst transforming the mixin class: [MAIN Applicator Phase -> randoassistant.client.mixins.json:InventoryScreenMixin from mod randoassistant -> Apply Methods -> (Lnet/minecraft/class_4185;)V:md59eed5$randoassistant$lambda$onInit$0$1 -> Transform Instructions -> INVOKESPECIAL com/bawnorton/randoassistant/mixin/client/InventoryScreenMixin$1::<init>(Lcom/bawnorton/randoassistant/mixin/client/InventoryScreenMixin;Lio/github/cottonmc/cotton/gui/GuiDescription;)V -> desc=Lio/github/cottonmc/cotton/gui/GuiDescription;]

Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: io.github.cottonmc.cotton.gui.GuiDescription

**Comment by Benjamin-Norton** [comment]
Can I see your full log? 

Just drag and drop the latest.log file from your .minecraft/logs folder

**Comment by obayko** [comment]
[latest.log](https://github.com/Benjamin-Norton/RandoAssistant/files/11024466/latest.log)

Did I do that correctly?

**Comment by Benjamin-Norton** [comment]
You are playing on 1.19.4, this mod is for 1.19.3, I have not yet updated it to 1.19.4.

**Comment by obayko** [comment]
That's so simple I didn't even consider that. I'll give it a go, thank you!!

**Comment by obayko** [comment]
That was absolutely it. Thank you and I can't wait to play it! 

So for anyone looking at this in the future, double check your mods and packs are all the same game version.
