### ISSUE TITLE
Crash when searching for lapis in graph

### ISSUE THREAD

**Issue by bbgarnett** [Benjamin-Norton/RandoAssistant#7]
[crash-2023-03-24_12.17.24-client.txt](https://github.com/Benjamin-Norton/RandoAssistant/files/11064832/crash-2023-03-24_12.17.24-client.txt)
I haven't noticed it up until I started typing in La in the search bar and that's as far as I get and it just crashes immediately every time. I also get a crash when scrolling to find the lapis and trying to click on it.

Thanks,

exit code -1

[crash-2023-03-24_12.08.59-client.txt](https://github.com/Benjamin-Norton/RandoAssistant/files/11064790/crash-2023-03-24_12.08.59-client.txt)

**Comment by Benjamin-Norton** [comment]
Hmm, not sure why this is happening. Could you send me your RandomAssistant folder? It'll be in your .minecraft folder.

**Comment by bbgarnett** [comment]
![explorer_0VKlAsBKu0](https://user-images.githubusercontent.com/20346293/227596663-db16877e-f01e-49d4-b3ae-ef499680f657.png)

assuming you want a screenshot?

**Comment by Benjamin-Norton** [comment]
Nope, need to see the inside of those files. Zip up the RandomAssistant folder and drag and drop that zip here.

**Comment by Benjamin-Norton** [comment]
Or just upload the files

**Comment by bbgarnett** [comment]
it's weird because it seems to only happen when typing in La yet I can search for other things normally like stripped or other items and haven't had a crash or at least haven't found another item that is causing a crash.

**Comment by Benjamin-Norton** [comment]
Hmm, I recreated your random assistant instance (via the files you sent me) and it doesn't crash when searching "La". Have you had this mod installed before? Like a previous version, as that can cause artifacting that doesn't get cleaned up properly.

**Comment by bbgarnett** [comment]
yes I am pretty sure I had 0.30 installed and updated to 0.31

**Comment by Benjamin-Norton** [comment]
Nothing major changed between those versions that could cause this. 
Can you try the 1.19.4 version (0.3.2) and see if that still causes the crash. I'm going to add a safety net to where this crash occurred to try and stop this from happening but I can't guarantee it as I can't replicate the crash.

**Comment by bbgarnett** [comment]
No worries I know your trying your best. I will update my game to 1.19.4 and the mod to 0.3.2 a little later and get back to you on if it is crashing when I have a chance.

**Comment by Benjamin-Norton** [comment]
Forget github auto closes when you mention issues in commits.

**Comment by bbgarnett** [comment]
Thanks and I did install/update everything to 1.19.4  and 03.2 and started a new world and found something that dropped lapis and then I went to the search bar and typed in La and it didn't crash. So thanks for helping and it looks like you found what was causing the issue and are fixing it so thanks again.
