### ISSUE TITLE
Game crashes when searching for items

### ISSUE THREAD

**Issue by DreamMojo** [Benjamin-Norton/RandoAssistant#9]
https://user-images.githubusercontent.com/129336275/228674765-0b6b52b5-f062-4f0c-9f51-c98201c861b5.mp4

[crash-2023-03-29_16.45.01-client.txt](https://github.com/Benjamin-Norton/RandoAssistant/files/11105718/crash-2023-03-29_16.45.01-client.txt)
the game may crash when right clicking on an item or searching for an item in the mod gui that is very far down.

**Comment by Benjamin-Norton** [comment]
Please update to the latest version, this has been fixed.

**Comment by DreamMojo** [comment]
> Please update to the latest version, this has been fixed.

ty
